
const BASE={blades:[["DranStrike","BX-49",1],["PhoenixWing","BX-23",1],["ImpactDrake","UX-11",1],["SilverWolf","UX-08",1],["ScorpioSpear","UX-14",1],["BulletGriffon","UX-19",1],["BahamutBlitz BK","CX-16",1],["SolEclipse D","CX-09",1],["WolfHunt F","CX-10",1]],ratchets:[["Integrated",1],["0-60",1],["0-70",1],["1-50",1],["3-80",1],["4-50",1],["5-70",1],["9-60",2]],bits:[["Disc Ball",1],["Free Ball",1],["Free Flat",1],["Gear Flat",1],["Hexa",1],["Ignition",1],["Low Rush",1],["Trans Kick",1],["Zap",1]]};
const DEFAULT={owned:structuredClone(BASE),deck:[{slot:"Bey 1",blade:"DranStrike",ratchet:"1-50",bit:"Low Rush",role:"Primary attacker"},{slot:"Bey 2",blade:"SilverWolf",ratchet:"9-60",bit:"Hexa",role:"Defense"},{slot:"Bey 3",blade:"PhoenixWing",ratchet:"9-60",bit:"Gear Flat",role:"Secondary attacker"},{slot:"Test Bey",blade:"BahamutBlitz BK",ratchet:"0-70",bit:"Ignition",role:"Balance / counter"}],matches:[],historical:[{a:"DranStrike 1-50 Low Rush",b:"SilverWolf 9-60 Hexa",aWins:7,bWins:5,aSpin:2,aBurst:0,aOver:12,aXtreme:5,bSpin:22,bBurst:0,bOver:4,bXtreme:0},{a:"DranStrike 1-50 Low Rush",b:"PhoenixWing 9-60 Gear Flat",aWins:7,bWins:5,aSpin:12,aBurst:1,aOver:6,aXtreme:3,bSpin:10,bBurst:0,bOver:2,bXtreme:3}],activeTest:{focus:0,opponent:3,target:12}};
let state=load();if(!state.owned)state.owned=structuredClone(BASE);if(!state.activeTest)state.activeTest={focus:0,opponent:3,target:12};save();let page="home",battle=null,pending=null;
function load(){try{return JSON.parse(localStorage.getItem("beylab-state"))||structuredClone(DEFAULT)}catch{return structuredClone(DEFAULT)}}function save(){localStorage.setItem("beylab-state",JSON.stringify(state))}
function name(x){return `${x.blade} ${x.ratchet} ${x.bit}`}function qty(list,n){let x=list.find(v=>v[0]===n);return x?x[x.length-1]:0}
function conflicts(){let d=state.deck.slice(0,3),o=[];for(let k of ["blade","ratchet","bit"]){let m={};d.forEach(x=>m[x[k]]=(m[x[k]]||0)+1);Object.entries(m).forEach(([p,n])=>{let q=k==="blade"?qty(state.owned.blades,p):k==="ratchet"?qty(state.owned.ratchets,p):qty(state.owned.bits,p);if(n>q)o.push(`${p} used ${n} times; owned ${q}.`)})}d.forEach(x=>{if(x.blade==="BulletGriffon"&&x.ratchet!=="Integrated")o.push("BulletGriffon requires Integrated ratchet.");if(x.blade!=="BulletGriffon"&&x.ratchet==="Integrated")o.push("Integrated is BulletGriffon-only.")});return [...new Set(o)]}
function aggregate(){let m={};function add(n,w,l,s,b,o,x,p,a){m[n]??={name:n,w:0,l:0,matches:0,spin:0,burst:0,over:0,xtreme:0,points:0,against:0};let z=m[n];z.w+=w;z.l+=l;z.matches+=w+l;z.spin+=s;z.burst+=b;z.over+=o;z.xtreme+=x;z.points+=p;z.against+=a}
state.historical.forEach(t=>{let ap=t.aSpin+2*t.aBurst+2*t.aOver+3*t.aXtreme,bp=t.bSpin+2*t.bBurst+2*t.bOver+3*t.bXtreme;add(t.a,t.aWins,t.bWins,t.aSpin,t.aBurst,t.aOver,t.aXtreme,ap,bp);add(t.b,t.bWins,t.aWins,t.bSpin,t.bBurst,t.bOver,t.bXtreme,bp,ap)});
state.matches.forEach(t=>{let c=(s,f)=>t.rounds.filter(r=>r.side===s&&r.finish===f).length,aw=t.winner===t.a?1:0,bw=1-aw;add(t.a,aw,bw,c("a","Spin"),c("a","Burst"),c("a","Over"),c("a","Xtreme"),t.aScore,t.bScore);add(t.b,bw,aw,c("b","Spin"),c("b","Burst"),c("b","Over"),c("b","Xtreme"),t.bScore,t.aScore)});return Object.values(m).map(x=>({...x,wr:x.matches?x.w/x.matches:0,diff:x.points-x.against}))}
function nav(){return `<nav>${[["home","⌂","Home"],["battle","⚔","Battle"],["deck","◈","Deck"],["analytics","▥","Analytics"],["data","⚙","Data"]].map(x=>`<button class="${page===x[0]?"active":""}" onclick="go('${x[0]}')"><span>${x[1]}</span>${x[2]}</button>`).join("")}</nav>`}
function render(){let v={home,battle:battleView,deck,analytics,data};document.getElementById("app").innerHTML=`<header><h1>Personal Beyblade X Tournament Lab</h1><p>Owned-parts tournament testing and analytics</p></header><main>${v[page]()}</main>${nav()}`}function go(p){page=p;render()}
function setTarget(v){state.activeTest.target=Math.max(1,Math.min(200,+v||12));save();render()}
function home(){let a=aggregate().find(x=>x.name==="DranStrike 1-50 Low Rush"),t=state.activeTest,focus=name(state.deck[t.focus]),opp=name(state.deck[t.opponent]),done=state.matches.filter(m=>(m.a===focus&&m.b===opp)||(m.a===opp&&m.b===focus)).length,remain=Math.max(0,t.target-done);return `<div class="card"><h2>Current decision</h2><div class="notice"><b>Keep DranStrike 1-50 Low Rush unchanged.</b><br>Existing evidence: ${a.w}-${a.l}, ${(a.wr*100).toFixed(1)}% win rate, +${a.diff} point differential.</div></div><div class="grid"><div class="metric"><b>${a.matches}</b><span>DranStrike matches</span></div><div class="metric"><b>${(a.wr*100).toFixed(1)}%</b><span>Win rate</span></div><div class="metric"><b>${state.matches.length}</b><span>New matches saved</span></div><div class="metric"><b>${conflicts().length||"✓"}</b><span>Deck legality</span></div></div><div class="card"><h3>Priority test</h3><p><b>${focus}</b><br><span class="muted">vs</span><br><b>${opp}</b></p><div class="progress"><div style="width:${Math.min(100,done/t.target*100)}%"></div></div><p class="muted">${done} of ${t.target} completed · ${remain} remaining</p><label>Target matches</label><div style="display:grid;grid-template-columns:1fr auto;gap:8px"><input id="target" type="number" min="1" max="200" value="${t.target}"><button class="btn secondary" onclick="setTarget(target.value)">Update</button></div><div class="actions"><button class="btn" onclick="start(${t.focus},${t.opponent})">Start next match</button></div></div>`}
function opts(list,s){return list.map(x=>`<option ${x[0]===s?"selected":""}>${x[0]}</option>`).join("")}
function deck(){return `<div class="card"><h2>Deck and Test Bey</h2>${state.deck.map((x,i)=>`<div class="deck-row"><div class="slot">${x.slot}</div><div><label>Blade</label><select onchange="upd(${i},'blade',this.value)">${opts(state.owned.blades,x.blade)}</select></div><div><label>Ratchet</label><select onchange="upd(${i},'ratchet',this.value)">${opts(state.owned.ratchets,x.ratchet)}</select></div><div><label>Bit</label><select onchange="upd(${i},'bit',this.value)">${opts(state.owned.bits,x.bit)}</select></div></div>`).join("")}<div class="notice">${conflicts().length?conflicts().join("<br>"):"Tournament deck is legal."}</div></div>`}function upd(i,k,v){state.deck[i][k]=v;save();render()}
function pair(a,b){if(a===b)return"Choose different slots.";let x=state.deck[a],y=state.deck[b];if(x.blade===y.blade&&qty(state.owned.blades,x.blade)<2)return`Only one ${x.blade} is owned.`;if(x.ratchet===y.ratchet&&qty(state.owned.ratchets,x.ratchet)<2)return`Only one ${x.ratchet} is owned.`;if(x.bit===y.bit&&qty(state.owned.bits,x.bit)<2)return`Only one ${x.bit} is owned.`;return""}
function start(a,b){let e=pair(a,b);if(e)return alert(e);battle={a:name(state.deck[a]),b:name(state.deck[b]),aScore:0,bScore:0,rounds:[]};page="battle";render()}
function battleView(){if(!battle)return`<div class="card"><h2>Start a match</h2><label>Combo A</label><select id="pa">${state.deck.map((x,i)=>`<option value="${i}">${x.slot}: ${name(x)}</option>`).join("")}</select><label>Combo B</label><select id="pb">${state.deck.map((x,i)=>`<option value="${i}" ${i===3?"selected":""}>${x.slot}: ${name(x)}</option>`).join("")}</select><div class="actions"><button class="btn" onclick="start(+pa.value,+pb.value)">Start</button></div></div>`;let done=battle.aScore>=4||battle.bScore>=4;return`<div class="card"><div class="scoreboard"><div><b>${battle.a}</b><div class="score">${battle.aScore}</div></div><div class="versus">VS</div><div><b>${battle.b}</b><div class="score">${battle.bScore}</div></div></div></div>${done?`<div class="card"><h2>${battle.aScore>battle.bScore?battle.a:battle.b} wins</h2><div class="actions"><button class="btn good" onclick="saveBattle()">Save</button><button class="btn secondary" onclick="undo()">Undo</button><button class="btn danger" onclick="cancel()">Discard</button></div></div>`:`<div class="card"><h3>${battle.a}</h3>${buttons("a")}</div><div class="card"><h3>${battle.b}</h3>${buttons("b")}</div><div class="actions"><button class="btn secondary" onclick="undo()">Undo</button><button class="btn danger" onclick="cancel()">Cancel</button></div>`}<div class="card"><h3>Rounds</h3>${battle.rounds.length?`<div class="scroll"><table><tr><th>#</th><th>Winner</th><th>Finish</th><th>Pts</th><th>Own</th></tr>${battle.rounds.map((r,i)=>`<tr><td>${i+1}</td><td>${r.side==="a"?battle.a:battle.b}</td><td>${r.finish}</td><td>${r.points}</td><td>${r.own?"Yes":""}</td></tr>`).join("")}</table></div>`:`<p class="muted">No rounds yet.</p>`}</div>${pending?modal():""}`}
function buttons(s){return`<div class="finish-grid">${[["Spin",1],["Burst",2],["Over",2],["Xtreme",3]].map(x=>`<button class="finish" onclick="finish('${s}','${x[0]}',${x[1]})">${x[0]}<small>${x[1]} pt</small></button>`).join("")}</div>`}
function finish(s,f,p){if(f==="Over"||f==="Xtreme"){pending={s,f,p};render()}else add(s,f,p,false)}function modal(){return`<div class="modal"><div class="card"><h3>Own Finish?</h3><p class="muted">Yes only if the losing Bey entered the zone without contact.</p><div class="actions"><button class="btn secondary" onclick="confirmOwn(false)">No</button><button class="btn danger" onclick="confirmOwn(true)">Yes</button></div></div></div>`}function confirmOwn(o){let p=pending;pending=null;add(p.s,p.f,p.p,o)}function add(s,f,p,o){battle.rounds.push({side:s,finish:f,points:p,own:o});s==="a"?battle.aScore+=p:battle.bScore+=p;render()}function undo(){if(pending){pending=null;return render()}let r=battle.rounds.pop();if(!r)return;r.side==="a"?battle.aScore-=r.points:battle.bScore-=r.points;render()}function cancel(){if(confirm("Discard match?")){battle=null;render()}}function saveBattle(){let w=battle.aScore>battle.bScore?battle.a:battle.b;state.matches.push({...battle,winner:w,date:new Date().toISOString()});save();battle=null;page="home";render()}
function analytics(){let a=aggregate().sort((x,y)=>y.wr-x.wr);return`<div class="card"><h2>Leaderboard</h2><div class="scroll"><table><tr><th>Combo</th><th>Record</th><th>Win %</th><th>Diff</th></tr>${a.map(x=>`<tr><td>${x.name}</td><td>${x.w}-${x.l}</td><td>${(x.wr*100).toFixed(1)}%</td><td>${x.diff>=0?"+":""}${x.diff}</td></tr>`).join("")}</table></div></div>`}
function addPart(cat,n,q,src){n=n.trim();q=Math.max(1,+q||1);if(!n)return alert("Enter a name.");let list=cat==="Blade"?state.owned.blades:cat==="Ratchet"?state.owned.ratchets:state.owned.bits,x=list.find(v=>v[0].toLowerCase()===n.toLowerCase());if(x)x[x.length-1]+=q;else list.push(cat==="Blade"?[n,src||"Manual",q]:[n,q]);save();render()}
function addSet(){let c=setCode.value.trim()||"Manual set",q=Math.max(1,+setQty.value||1);if(!setBlade.value&&!setRatchet.value&&!setBit.value)return alert("Enter at least one part.");if(setBlade.value)addPart("Blade",setBlade.value,q,c);if(setRatchet.value)addPart("Ratchet",setRatchet.value,q,c);if(setBit.value)addPart("Bit",setBit.value,q,c);alert(`${c} added.`)}
function data(){let rows=(title,list)=>`<tr><th colspan="3">${title}</th></tr>${list.map(x=>`<tr><td>${x[0]}</td><td>${x[x.length-1]}</td><td>${x.length===3?x[1]:""}</td></tr>`).join("")}`;return`<div class="card"><h2>Collection manager</h2><h3>Add individual part</h3><div class="grid"><div><label>Category</label><select id="pc"><option>Blade</option><option>Ratchet</option><option>Bit</option></select></div><div><label>Name</label><input id="pn"></div><div><label>Qty</label><input id="pq" type="number" value="1"></div><div><label>Source</label><input id="ps"></div></div><div class="actions"><button class="btn" onclick="addPart(pc.value,pn.value,pq.value,ps.value)">Add part</button></div><hr><h3>Add product/set</h3><div class="grid"><div><label>Code</label><input id="setCode"></div><div><label>Blade</label><input id="setBlade"></div><div><label>Ratchet</label><input id="setRatchet"></div><div><label>Bit</label><input id="setBit"></div><div><label>Qty</label><input id="setQty" type="number" value="1"></div></div><div class="actions"><button class="btn good" onclick="addSet()">Add set</button></div></div><div class="card"><h3>Owned parts</h3><div class="scroll"><table><tr><th>Part</th><th>Qty</th><th>Source</th></tr>${rows("Blades",state.owned.blades)}${rows("Ratchets",state.owned.ratchets)}${rows("Bits",state.owned.bits)}</table></div></div><div class="card"><h3>Backup</h3><div class="actions"><button class="btn" onclick="backup()">Export</button><button class="btn danger" onclick="reset()">Reset</button></div></div>`}
function backup(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="beylab-backup.json";a.click()}function reset(){if(confirm("Reset all data?")){state=structuredClone(DEFAULT);save();render()}}
addEventListener("load",()=>{if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");render()});
