if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(registrations=>registrations.forEach(registration=>registration.unregister())).catch(()=>{});if('caches' in globalThis)caches.keys().then(keys=>Promise.all(keys.map(key=>caches.delete(key)))).catch(()=>{});}
import {CATALOG} from './catalog.js';import {getState,setState,mutate,subscribe,reset,exportState,importState} from './state.js';import {startRouter,currentRoute,go} from './router.js';import {productToEntry,customLoosePart} from './inventory.js';import {analyze,chooseTest,recordEvidence} from './coach.js';import {renderCollection,setCatalogQuery,setCatalogFilter} from './collection.js';import {renderDeck} from './deck.js';import {renderTest} from './test.js';import {renderMatch} from './match.js';
const app=document.querySelector('#app'),toastNode=document.querySelector('#toast');let analysisTimer=null,toastTimer=null;
function toast(text){toastNode.textContent=text;toastNode.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastNode.classList.remove('show'),2200)}
function routeRenderer(route=currentRoute()){document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===route));const s=getState();app.innerHTML=route==='collection'?renderCollection(s):route==='deck'?renderDeck(s):route==='test'?renderTest(s):renderMatch(s);document.querySelector('#headerStatus').textContent=s.analysisPending?'Coach analyzing…':s.analysis?.ready?`${s.inventory.length} entries · deck ready`:s.inventory.length?`${s.inventory.length} entries · collection incomplete`:'Inventory empty';if(route==='test'&&s.analysis?.ready&&!s.testSession)prepareTest();}
function scheduleAnalysis(){clearTimeout(analysisTimer);const s=getState();setState({analysisPending:true,analysis:null,selectedDeckId:null,testSession:null,testResults:[]},{save:false});analysisTimer=setTimeout(()=>{const now=getState();const result=analyze(now.inventory,now.evidence,now.locks);setState({analysis:result,analysisPending:false,selectedDeckId:result.decks[0]?.id||null,testSession:null,testResults:[]},{save:false});},40)}
function prepareTest(){const s=getState(),deck=s.analysis.decks.find(d=>d.id===s.selectedDeckId)||s.analysis.decks[0];const test=chooseTest(deck,s.analysis.combos,s.evidence);setState({testSession:test,testResults:[]},{save:false})}
subscribe(()=>routeRenderer());startRouter(routeRenderer);
addEventListener('click',e=>{const el=e.target.closest('button,[data-add-product],[data-remove-entry]');if(!el)return;if(el.dataset.addProduct){const p=CATALOG.find(x=>x.id===el.dataset.addProduct);if(!p)return;mutate(s=>s.inventory.push(productToEntry(p)));toast(`${p.code} added`);scheduleAnalysis();return}if(el.dataset.removeEntry){mutate(s=>{s.inventory=s.inventory.filter(x=>x.id!==el.dataset.removeEntry);s.locks=[]});scheduleAnalysis();return}if(el.dataset.filter){setCatalogFilter(el.dataset.filter);routeRenderer();return}if(el.dataset.action==='open-loose'){document.querySelector('#looseDialog')?.showModal();return}if(el.dataset.action==='save-loose'){const name=document.querySelector('#looseName').value.trim();if(!name)return toast('Enter a part name.');const entry=customLoosePart(document.querySelector('#looseCategory').value,name,document.querySelector('#looseRole').value);mutate(s=>s.inventory.push(entry));document.querySelector('#looseDialog').close();scheduleAnalysis();toast('Loose part added');return}if(el.dataset.lockCombo){mutate(s=>{const sig=el.dataset.lockCombo;s.locks=s.locks.includes(sig)?s.locks.filter(x=>x!==sig):s.locks.length<2?[...s.locks,sig]:[s.locks[1],sig]});scheduleAnalysis();return}if(el.dataset.selectDeck){setState({selectedDeckId:el.dataset.selectDeck,testSession:null,testResults:[]});return}if(el.dataset.testResult){const results=[...(getState().testResults||[]),el.dataset.testResult].slice(0,3);if(results.length<3){setState({testResults:results},{save:false});return}const session=getState().testSession;mutate(s=>s.evidence.push(recordEvidence(session,results)));toast('Three-battle test saved');scheduleAnalysis();go('deck');return}if(el.dataset.scoreSide){mutate(s=>{const side=el.dataset.scoreSide,points=Number(el.dataset.points);s.match[side]=Math.min(7,s.match[side]+points);s.match.battles.push({side,points,finish:el.dataset.finish})});return}if(el.dataset.action==='reset-match'){setState({match:{me:0,opponent:0,battles:[]}});return}if(el.dataset.action==='open-settings'){document.querySelector('#settingsDialog').showModal();return}if(el.dataset.action==='reset-app'){if(confirm('Delete all inventory and evidence?')){reset();document.querySelector('#settingsDialog').close();go('collection')}return}if(el.dataset.action==='export-data'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([exportState()],{type:'application/json'}));a.download='x-tournament-director-backup.json';a.click();URL.revokeObjectURL(a.href);return}});
addEventListener('input',e=>{if(e.target.id==='catalogSearch'){setCatalogQuery(e.target.value);routeRenderer()}});
addEventListener('change',async e=>{if(e.target.dataset.action==='import-data'){try{importState(await e.target.files[0].text());scheduleAnalysis();document.querySelector('#settingsDialog').close();toast('Backup restored')}catch(err){toast(err.message)}}});
if(getState().inventory.length)scheduleAnalysis();
