import {generateCombinations,isLegalDeck,isDisjointPair} from './combinations.js';
import {physicalParts} from './inventory.js';
export const ARCHETYPES=[{id:'attack',name:'Heavy attack',v:{atk:88,sta:34,def:46,ctl:50,burst:54,recoil:72,ko:89,mass:67}},{id:'stamina',name:'Pure stamina',v:{atk:30,sta:91,def:61,ctl:78,burst:58,recoil:24,ko:28,mass:52}},{id:'defense',name:'Defense / counter',v:{atk:43,sta:63,def:86,ctl:71,burst:78,recoil:28,ko:41,mass:68}},{id:'balance',name:'Adaptive balance',v:{atk:61,sta:62,def:62,ctl:66,burst:62,recoil:46,ko:60,mass:57}}];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function evidenceFor(sig,evidence){let w=0,l=0;for(const e of evidence)if(e.subjectSignature===sig){w+=e.wins||0;l+=e.losses||0}return {wins:w,losses:l,games:w+l}}
function winChance(c,a){const v=c.profile,o=a.v;const offense=(v.atk*.42+v.ko*.35+v.mass*.15-v.recoil*.18);const staying=(v.sta*.34+v.def*.26+v.ctl*.22+v.burst*.18);const opp=(o.atk+o.sta+o.def+o.ko)/4;return clamp(.5+(offense*.45+staying*.55-opp)*.007,.18,.82)}
function posterior(c,evidence){const e=evidenceFor(c.signature,evidence);const prior=comboBase(c);return {mean:(prior*6+e.wins)/(6+e.games),games:e.games}}
function comboBase(c){const v=c.profile;return clamp((v.atk*.16+v.sta*.17+v.def*.14+v.ctl*.16+v.burst*.1+v.ko*.2+v.mass*.1-v.recoil*.08)/100,.2,.86)}
function matchupMap(c){return Object.fromEntries(ARCHETYPES.map(a=>[a.id,winChance(c,a)]))}
function individualScore(c,evidence){const p=posterior(c,evidence),m=matchupMap(c),floor=Math.min(...Object.values(m));const critical=clamp((c.profile.ko*.65+c.profile.atk*.35-c.profile.recoil*.18)/100,0,1);return p.mean*.38+floor*.3+critical*.18+(c.profile.ctl/100)*.14}
function deckMetrics(combos,evidence){const maps=combos.map(matchupMap);const coverage=ARCHETYPES.map(a=>Math.max(...maps.map(m=>m[a.id])));const backup=ARCHETYPES.map(a=>maps.map(m=>m[a.id]).sort((x,y)=>y-x)[1]);const floor=Math.min(...coverage),backupFloor=Math.min(...backup);const roles=new Set(combos.map(c=>c.role)).size;const criticalFloor=Math.min(...combos.map(c=>clamp((c.profile.ko*.65+c.profile.atk*.35-c.profile.recoil*.2)/100,0,1)));const risk=combos.reduce((s,c)=>s+c.profile.recoil/100,0)/3;const control=combos.reduce((s,c)=>s+c.profile.ctl/100,0)/3;const evidenceGames=combos.reduce((s,c)=>s+evidenceFor(c.signature,evidence).games,0);const score=floor*.36+backupFloor*.2+criticalFloor*.16+control*.1+(roles/3)*.1-risk*.08+Math.min(evidenceGames/60,.05);return {score,coverage,backup,floor,backupFloor,criticalFloor,risk,control,roles,evidenceGames}}
function permutations(a){return [[a[0],a[1],a[2]],[a[0],a[2],a[1]],[a[1],a[0],a[2]],[a[1],a[2],a[0]],[a[2],a[0],a[1]],[a[2],a[1],a[0]]]}
function orderScore(order){return order.reduce((s,c,i)=>s+individualScore(c,[])*[1,.86,.72][i],0)}
function shortlist(combos,evidence){const sets=[...ARCHETYPES.map(a=>[...combos].sort((x,y)=>winChance(y,a)-winChance(x,a)).slice(0,24)),[...combos].sort((x,y)=>individualScore(y,evidence)-individualScore(x,evidence)).slice(0,40)];const byCore=new Map();for(const c of combos){const core=c.parts.find(p=>['blade','main','metal'].includes(p.category))?.canonicalKey||c.signature;const arr=byCore.get(core)||[];arr.push(c);byCore.set(core,arr)}for(const arr of byCore.values())sets.push(arr.sort((x,y)=>individualScore(y,evidence)-individualScore(x,evidence)).slice(0,5));return [...new Map(sets.flat().map(c=>[c.signature,c])).values()].slice(0,150)}
export function analyze(inventory,evidence=[],locks=[]){const combos=generateCombinations(physicalParts(inventory));if(combos.length<3)return {ready:false,combos,decks:[],reason:'Not enough legal combinations.'};const candidates=shortlist(combos,evidence);const locked=locks.map(sig=>combos.find(c=>c.signature===sig)).filter(Boolean);const decks=[];for(let i=0;i<candidates.length;i++)for(let j=i+1;j<candidates.length;j++)for(let k=j+1;k<candidates.length;k++){const trio=[candidates[i],candidates[j],candidates[k]];if(locked.some(l=>!trio.some(c=>c.signature===l.signature)))continue;if(!isLegalDeck(trio))continue;const metrics=deckMetrics(trio,evidence);const order=permutations(trio).sort((a,b)=>orderScore(b)-orderScore(a))[0];decks.push({id:trio.map(c=>c.signature).sort().join('::'),combos:trio,order,metrics});}decks.sort((a,b)=>b.metrics.score-a.metrics.score);return {ready:decks.length>0,combos,decks:decks.slice(0,8),evaluated:decks.length}}
export function explainCombo(combo,deck,evidence){const map=matchupMap(combo),sorted=Object.entries(map).sort((a,b)=>b[1]-a[1]),best=ARCHETYPES.find(a=>a.id===sorted[0][0]),worst=ARCHETYPES.find(a=>a.id===sorted.at(-1)[0]),post=posterior(combo,evidence);const roleReasons={Attack:'Provides the deck’s primary high-point KO pressure.',Stamina:'Protects the deck against long-spin and endurance matchups.',Defense:'Absorbs aggressive openings and reduces self-KO exposure.',Balance:'Covers multiple opponent styles without a severe specialization gap.'};const launch=combo.role==='Attack'?(combo.profile.ctl>=62?'Controlled hard launch with a slight tilt.':'Hard launch; reduce angle if self-KOs appear.'):combo.role==='Stamina'?'Level launch toward a clean center path.':combo.role==='Defense'?'Moderate launch with a slight counter-tilt.':'Controlled launch; adjust angle to the opponent.';return {why:roleReasons[combo.role]||roleReasons.Balance,beats:best.name,struggles:worst.name,launch,confidence:post.games>=20?'High':post.games>=6?'Developing':'Prior only',games:post.games,matchups:map}}
export function chooseTest(deck,allCombos,evidence){if(!deck)return null;const subject=[...deck.combos].sort((a,b)=>evidenceFor(a.signature,evidence).games-evidenceFor(b.signature,evidence).games)[0];const weakest=ARCHETYPES.map(a=>({a,p:winChance(subject,a)})).sort((x,y)=>x.p-y.p)[0].a;const opponents=allCombos.filter(c=>c.signature!==subject.signature&&isDisjointPair(subject,c));if(!opponents.length)return null;const opponent=opponents.map(c=>({c,fit:winChance(c,{id:'subject',name:'Subject',v:subject.profile})+(c.role.toLowerCase()===weakest.id?.toLowerCase()?0.08:0)})).sort((a,b)=>b.fit-a.fit)[0].c;return {subject,opponent,weakness:weakest.name,reason:`This owned opponent stresses ${subject.name}'s weakest modeled matchup: ${weakest.name}.`,launch:explainCombo(subject,deck,evidence).launch}}
export function recordEvidence(session,results){const wins=results.filter(x=>x==='win').length,losses=results.filter(x=>x==='loss').length;return {id:crypto.randomUUID?.()||String(Date.now()),date:new Date().toISOString(),subjectSignature:session.subject.signature,subjectName:session.subject.name,opponentSignature:session.opponent.signature,opponentName:session.opponent.name,wins,losses}}
