import {CATALOG} from '../catalog.js';import {esc,pageHead} from './common.js';
let query='',filter='all';
function partsText(product){return product.beys.map(b=>b.system==='standard'?`${b.blade} ${b.ratchet}${b.bit}`:b.system==='integrated'?`${b.blade} ${b.bit}`:b.system==='cx-standard'?`${b.lock}${b.main} ${b.assist}${b.ratchet}${b.bit}`:b.system==='cx-expand'?`${b.lock}${b.over}${b.metal} ${b.assist}${b.ratchet}${b.bit}`:`${b.lock}${b.main} ${b.assist}${b.fused}`).join(' · ')}
export function renderCollection(state){const results=CATALOG.filter(p=>(filter==='all'||p.line===filter||(filter==='random'&&p.random)||(filter==='limited'&&p.limited))&&(!query||`${p.code} ${p.title} ${p.type}`.toLowerCase().includes(query))).slice(0,120);const inventory=state.inventory;return `${pageHead('Step 1','Build your owned collection','Nothing is preloaded. Add only products or loose parts that you physically own.')}
<section class="card accent command"><div><div class="eyebrow">Collection status</div><h2>${inventory.length?`${inventory.length} owned ${inventory.length===1?'entry':'entries'}`:'Inventory is empty'}</h2><p>${state.analysis?.ready?'A legal tournament deck is available.':'Add enough compatible parts for three legal Beys.'}</p></div>${state.analysis?.ready?'<a class="button" href="#/deck">View deck →</a>':''}</section>
<div class="grid two" style="margin-top:16px"><section class="card"><h2>Known sets with Beys</h2><p class="muted">Search by product code or Bey name. Catalog items remain unowned until added.</p><div class="catalog-tools"><input class="field" id="catalogSearch" placeholder="Example: UX-08 or SilverWolf" value="${esc(query)}"><button class="button secondary" data-action="open-loose">Add loose part</button></div><div class="filter-row">${['all','BX','UX','CX','random','limited'].map(f=>`<button class="filter ${filter===f?'active':''}" data-filter="${f}">${f==='all'?'All':f}</button>`).join('')}</div><div class="catalog-list">${results.map(p=>`<article class="catalog-item"><div><strong>${esc(p.code)} · ${esc(p.title)}</strong><small>${esc(p.type)} · ${esc(partsText(p))}</small></div><button class="mini" data-add-product="${esc(p.id)}" aria-label="Add ${esc(p.title)}">+</button></article>`).join('')||'<p class="muted">No catalog matches.</p>'}</div></section>
<section class="card"><h2>Owned inventory</h2><p class="muted">Each row is one physical copy. Add a set again when you own another copy.</p><div class="inventory-list">${inventory.length?inventory.map(e=>`<article class="inventory-item"><div><strong>${esc(e.code)} · ${esc(e.name)}</strong><small>${e.parts.length} parts · ${esc(e.type||e.kind)}</small><div class="part-pills">${e.parts.slice(0,7).map(p=>`<span class="pill">${esc(p.name)}</span>`).join('')}</div></div><button class="mini" data-remove-entry="${esc(e.id)}" aria-label="Remove ${esc(e.name)}">×</button></article>`).join(''):'<div class="empty"><div class="empty-icon">＋</div><h3>No owned items yet</h3><p class="muted">Use the catalog to add your first set.</p></div>'}</div></section></div>
<dialog id="looseDialog" class="dialog"><form method="dialog"><div class="dialog-head"><h2>Add loose part</h2><button class="icon-button" value="cancel">×</button></div><label>Part category<select class="field" id="looseCategory"><option value="blade">Blade</option><option value="ratchet">Ratchet</option><option value="bit">Bit</option><option value="lock">CX Lock</option><option value="main">CX Main Blade</option><option value="assist">CX Assist Blade</option><option value="over">CX Over Blade</option><option value="metal">CX Metal Blade</option><option value="fused">Integrated Bit</option></select></label><label>Part name<input class="field" id="looseName" placeholder="Example: 9-60"></label><label>Role estimate<select class="field" id="looseRole"><option>balance</option><option>attack</option><option>stamina</option><option>defense</option></select></label><div class="button-row" style="margin-top:16px"><button type="button" class="button" data-action="save-loose">Add part</button></div></form></dialog>`}
export function setCatalogQuery(v){query=v.toLowerCase()}export function setCatalogFilter(v){filter=v}
