import {canonical,combine,roleFrom} from './profiles.js';
function restricted(part){if(part.category!=='lock')return true;const k=canonical(part.name);return ['valkyrie','warukyuure','emperor'].some(x=>k.includes(x))}
function nameFor(parts,system){const get=c=>parts.find(p=>p.category===c);const bit=get('bit'),rat=get('ratchet'),blade=get('blade');if(blade)return system==='integrated'?`${blade.name} ${bit?.code||bit?.name}`:`${blade.name} ${rat?.name}${bit?.code||bit?.name}`;const lock=get('lock'),main=get('main'),over=get('over'),metal=get('metal'),assist=get('assist'),fused=get('fused');const core=main?`${lock?.name||''}${main.name}`:`${lock?.name||''}${over?.name||''}${metal?.name||''}`;return fused?`${core} ${assist?.name||''}${fused.code||fused.name}`:`${core} ${assist?.name||''}${rat?.name||''}${bit?.code||bit?.name}`}
function make(parts,system){if(new Set(parts.map(p=>p.physicalId)).size!==parts.length)return null;const vector=combine(parts),signature=parts.map(p=>`${p.category}:${p.canonicalKey}`).sort().join('|');return {signature,name:nameFor(parts,system).replace(/\s+/g,' ').trim(),system,role:roleFrom(vector),profile:vector,parts,allocations:[parts.map(p=>p.physicalId)],canonicalParts:parts.map(p=>({category:p.category,key:p.canonicalKey,restricted:restricted(p)})),sourceLabels:[...new Set(parts.map(p=>p.source))]}}
export function generateCombinations(g){const raw=[];for(const b of g.blade){if(b.integratedRatchet){for(const bit of g.bit)raw.push(make([b,bit],'integrated'))}else for(const r of g.ratchet)for(const bit of g.bit)raw.push(make([b,r,bit],'standard'))}for(const l of g.lock)for(const m of g.main)for(const a of g.assist)for(const r of g.ratchet)for(const b of g.bit)raw.push(make([l,m,a,r,b],'cx-standard'));for(const l of g.lock)for(const o of g.over)for(const m of g.metal)for(const a of g.assist)for(const r of g.ratchet)for(const b of g.bit)raw.push(make([l,o,m,a,r,b],'cx-expand'));for(const l of g.lock)for(const m of g.main)for(const a of g.assist)for(const f of g.fused)raw.push(make([l,m,a,f],'cx-integrated'));
 const map=new Map();for(const c of raw.filter(Boolean)){const prev=map.get(c.signature);if(prev)prev.allocations.push(c.allocations[0]);else map.set(c.signature,c)}return [...map.values()]}
export function compatibleNames(a,b){for(const pa of a.canonicalParts)for(const pb of b.canonicalParts)if(pa.category===pb.category&&pa.key===pb.key&&(pa.restricted||pb.restricted))return false;return true}
export function allocateDeck(combos){function walk(i,used,allocs){if(i===combos.length)return allocs;for(const allocation of combos[i].allocations){if(allocation.some(id=>used.has(id)))continue;const next=new Set(used);allocation.forEach(id=>next.add(id));const result=walk(i+1,next,[...allocs,allocation]);if(result)return result}return null}return walk(0,new Set(),[])}
export function isLegalDeck(combos){if(combos.length!==3)return false;for(let i=0;i<3;i++)for(let j=i+1;j<3;j++)if(!compatibleNames(combos[i],combos[j]))return false;return Boolean(allocateDeck(combos))}
export function isDisjointPair(a,b){return compatibleNames(a,b)&&Boolean(allocateDeck([a,b]))}
