export const KEYS=['atk','sta','def','ctl','burst','recoil','ko','mass'];
export const ROLE_PRESETS={attack:{atk:82,sta:28,def:38,ctl:46,burst:48,recoil:68,ko:82,mass:56},balance:{atk:56,sta:56,def:56,ctl:60,burst:58,recoil:45,ko:56,mass:53},stamina:{atk:30,sta:86,def:58,ctl:76,burst:56,recoil:24,ko:28,mass:48},defense:{atk:38,sta:58,def:86,ctl:72,burst:78,recoil:26,ko:38,mass:64}};
export const CATEGORY_WEIGHT={blade:1,lock:.18,main:.66,over:.34,metal:.66,assist:.3,ratchet:.22,bit:.5,fused:.5};
export const BIT_INFO={F:['Flat','attack'],LF:['Low Flat','attack'],GF:['Gear Flat','attack'],A:['Accel','attack'],Q:['Quake','attack'],R:['Rush','attack'],C:['Cyclone','attack'],LR:['Low Rush','attack'],UF:['Under Flat','attack'],J:['Jolt','attack'],K:['Kick','attack'],GR:['Gear Rush','attack'],FF:['Free Flat','attack'],RA:['Rubber Accel','attack'],I:['Ignition','attack'],B:['Ball','stamina'],O:['Orb','stamina'],GB:['Gear Ball','stamina'],DB:['Disc Ball','stamina'],G:['Glide','stamina'],LO:['Low Orb','stamina'],DS:['Disc Spike','stamina'],FB:['Free Ball','stamina'],N:['Needle','defense'],HN:['High Needle','defense'],S:['Spike','defense'],D:['Dot','defense'],GN:['Gear Needle','defense'],H:['Hexa','defense'],MN:['Metal Needle','defense'],BS:['Bound Spike','defense'],UN:['Under Needle','defense'],W:['Wedge','defense'],WB:['Wall Ball','defense'],WW:['Wide Wedge','defense'],Y:['Yielding','defense'],Nr:['Needle Rush','defense'],T:['Taper','balance'],P:['Point','balance'],HT:['High Taper','balance'],GP:['Gear Point','balance'],U:['Unite','balance'],E:['Elevate','balance'],TP:['Trans Point','balance'],L:['Level','balance'],Z:['Zap','balance'],M:['Merge','balance'],GU:['Gear Unite','balance'],TK:['Trans Kick','balance'],V:['Vortex','balance']};
const OVERRIDES={
'blade:scorpiospear':[66,47,54,59,55,54,70,49],'blade:silverwolf':[31,93,67,82,60,20,27,55],'blade:phoenixwing':[87,45,54,60,56,75,86,61],'blade:impactdrake':[93,27,48,60,59,73,94,66],'blade:dranstrike':[89,43,58,71,68,62,90,68],'blade:bulletgriffon':[58,74,77,64,72,42,62,88],
'main:hunt':[57,75,65,66,56,41,57,56],'main:eclipse':[67,62,57,60,54,57,66,54],'metal:blitz':[88,27,43,42,55,75,90,69],
'bit:free-ball':[34,84,59,74,54,28,32,50],'bit:disc-ball':[35,82,62,70,53,29,34,50],'bit:gear-flat':[79,29,37,36,52,73,80,50],'bit:low-rush':[78,36,47,63,59,59,79,50],'bit:free-flat':[72,47,51,66,58,51,73,50],'bit:hexa':[41,61,77,72,77,30,40,50]
};
export const canonical=v=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export function profile(role='balance',category='blade',name=''){const override=OVERRIDES[`${category}:${canonical(name)}`];if(override)return Object.fromEntries(KEYS.map((k,i)=>[k,override[i]]));const base=ROLE_PRESETS[role]||ROLE_PRESETS.balance,w=CATEGORY_WEIGHT[category]||.3;return Object.fromEntries(KEYS.map(k=>[k,Math.round(50+(base[k]-50)*w)]))}
export function bitDetails(code){return BIT_INFO[String(code||'').trim()]||[String(code||'Unknown Bit'),'balance']}
export function combine(parts){const total=parts.reduce((s,p)=>s+(CATEGORY_WEIGHT[p.category]||.3),0)||1;return Object.fromEntries(KEYS.map(k=>[k,Math.round(parts.reduce((s,p)=>s+(p.profile?.[k]??50)*(CATEGORY_WEIGHT[p.category]||.3),0)/total)]))}
export function roleFrom(v){const scores={Attack:v.atk+v.ko-v.recoil*.25,Stamina:v.sta+v.ctl*.35,Defense:v.def+v.burst*.35};const sorted=Object.entries(scores).sort((a,b)=>b[1]-a[1]);return sorted[0][1]-sorted[1][1]<10?'Balance':sorted[0][0]}
