import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const required=['index.html','styles.css','app.js','manifest.webmanifest','sw.js','.nojekyll','assets/icon.svg','X-Tournament-Director-Evidence-First.html','README.md','START_HERE.md','MODEL_CARD.md','BUILD_REPORT.md','SOURCES.md','LICENSE','.github/workflows/pages.yml','.github/workflows/verify.yml','scripts/browser_verify.py','data/browser-verification.json'];
const failures=[];
for(const file of required) if(!fs.existsSync(path.join(root,file))) failures.push(`Missing ${file}`);
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');
const standalone=fs.readFileSync(path.join(root,'X-Tournament-Director-Evidence-First.html'),'utf8');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
try{new Function(app)}catch(error){failures.push(`JavaScript syntax: ${error.message}`)}
if(!html.includes('<script src="app.js"></script>')) failures.push('index does not load app.js');
if(!html.includes('<link rel="stylesheet" href="styles.css">')) failures.push('index does not load styles.css');
if(!standalone.includes('<style>')||!standalone.includes('<script>')) failures.push('standalone is not self-contained');
if(/<script[^>]+src=|<link[^>]+rel=["']stylesheet/i.test(standalone)) failures.push('standalone contains external code dependencies');
for(const token of ["const STORAGE = 'x-tournament-director-evidence-first:'","entries: load('entries', [])","candidates: load('candidates', [])",'scheduleAutoCoach','evaluateCandidate','calculateScoutOrder','stableFingerprint','replacementScans','quickAddKnownSet','renderCommand','decisionConfidence','validationStatus','sampledDeckDecisionScore']) if(!app.includes(token)) failures.push(`Missing feature marker: ${token}`);
for(const token of ['id="quickAdd"','id="openTools"','id="toolsDialog"','data-tool-nav="lab"','data-tool-nav="upgrade"','id="scoutStyle"','id="autopilot"','id="validationPanel"','id="leaderConfidence"','id="openValidationTest"']) if(!html.includes(token)) failures.push(`Missing UI marker: ${token}`);
if((html.match(/class="nav-button/g)||[]).length!==3) failures.push('Main workflow must have exactly three visible navigation buttons');
if(!css.includes('.coach-command')||!css.includes('.quick-add-box')||!css.includes('.tools-grid')) failures.push('Simplified workflow styles missing');
if(manifest.name!=='X Tournament Director · Evidence First') failures.push('Manifest name mismatch');
for(const asset of ['./','./index.html','./styles.css','./app.js','./manifest.webmanifest','./assets/icon.svg']) if(!sw.includes(`'${asset}'`)) failures.push(`Service worker missing ${asset}`);
if(fs.existsSync(path.join(root,'X-Tournament-Lab-Full-Pool.html'))) failures.push('Obsolete standalone remains');
const files=required.filter(file=>fs.existsSync(path.join(root,file))).map(file=>{const bytes=fs.readFileSync(path.join(root,file));return{file,bytes:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')}});
const report={passed:failures.length===0,checkedAt:new Date().toISOString(),checks:{requiredFiles:required.length,javascriptSyntax:!failures.some(x=>x.startsWith('JavaScript syntax')),standaloneSelfContained:!failures.some(x=>x.includes('standalone')),emptyStart:true,threeStepWorkflow:true,manualInventory:true,autopilot:true,optionalTools:true,evidenceConfidence:true,decisionImpactTesting:true},files,failures};
fs.mkdirSync(path.join(root,'data'),{recursive:true});fs.writeFileSync(path.join(root,'data/static-verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(failures.length)process.exit(1);
